define({
    root: ({
        widgets: ({
            "geoCoding" : {
            "zoomTo": "Zoom to Feature",
            "noAddress": "No Point Address",
            "clear": "Clear Selection",
            "instructions" : 
                "Click the map to get location address.",
            "Location": "Location",
            "Address": "Address:",
            "Block": "Block:",
            "City": "City:",
            "CountryCode": "Country Code:",
            "District": "District:",
            "MetroArea": "Metro Area:",
            "Neighborhood": "Neighborhood:",
            "PlaceName": "Place Name:",
            "PostalCode": "Postal Code:",
            "Region": "Region:",
            "Sector": "Sector:",
            "Territory": "Territory:",
            "Type": "Type:",
            "Addr_type": "Addr Type:"
            }
        })
    }),
    "ar": 0,
    "cs": 0,
    "da": 0,
    "de": 0,
    "el": 0,
    "es": 0,
    "et": 0,
    "fi": 0,
    "fr": 1,
    "he": 0,
    "it": 0,
    "ja": 0,
    "ko": 0,
    "lt": 0,
    "lv": 0,
    "nl": 0,
    "nb": 0,
    "pl": 0,
    "pt-br": 0,
    "pt-pt": 0,
    "ro": 0,
    "ru": 0,
    "sv": 0,
    "tr": 0,
    "th": 0,
    "vi": 0,
    "zh-cn": 0
});
